### ISSUE TITLE
Segmentation fault in Escargot::Object::setOwnDataPropertyUtilForObjectInner

### ISSUE THREAD

**Issue by renatahodovan** [pando-project/escargot#130]
###### Escargot version:

```
Checked revision: bfb1b7d
Build command: cmake -H. -Bout -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=debug -DESCARGOT_OUTPUT=bin -GNinja && ninja -C out
```

###### OS:

```
Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
var r = / /;
Object.defineProperty(r, 'global', {value: false});
```

###### Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555555f0c65 in Escargot::Object::setOwnDataPropertyUtilForObjectInner (this=0x7ffff45eed70, state=..., idx=2, item=..., newValue=...) at ../src/runtime/Object.h:885
#2  0x00005555557927b4 in Escargot::Object::defineOwnProperty (this=0x7ffff45eed70, state=..., P=..., desc=...) at ../src/runtime/Object.cpp:652
#3  0x000055555579c239 in Escargot::RegExpObject::defineOwnProperty (this=0x7ffff45eed70, state=..., P=..., desc=...) at ../src/runtime/RegExpObject.cpp:180
#4  0x00005555556bdedf in Escargot::Object::defineOwnPropertyThrowsException (this=0x7ffff45eed70, state=..., P=..., desc=...) at ../src/runtime/Object.h:708
#5  0x00005555557405e2 in Escargot::builtinObjectDefineProperty (state=..., thisValue=..., argc=3, argv=0x7fffffffdb18, isNewExpression=false) at ../src/runtime/GlobalObjectBuiltinObject.cpp:164
#6  0x00005555556c4bc0 in Escargot::FunctionObject::processCall (this=0x7ffff466ae30, state=..., receiverSrc=..., argc=@0x7fffffffdaa0: 3, argv=0x7fffffffdb18, isNewExpression=false)
    at ../src/runtime/FunctionObject.cpp:332
#7  0x00005555555f16c0 in Escargot::FunctionObject::call (state=..., callee=..., receiver=..., argc=@0x7fffffffdaa0: 3, argv=0x7fffffffdb18) at ../src/runtime/FunctionObject.h:105
#8  0x00005555555f484c in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff46723d0, programCounter=93824998898648, registerFile=0x7fffffffdb00, initAddressFiller=0x7fffffffdb98)
    at ../src/interpreter/ByteCodeInterpreter.cpp:524
#9  0x0000555555621877 in Escargot::Script::execute (this=0x7ffff45eb4f0, state=..., isEvalMode=false, needNewEnv=false, isOnGlobal=true) at ../src/parser/Script.cpp:80
#10 0x00005555556219c9 in Escargot::Script::<lambda()>::operator()(void) const (__closure=0x7fffffffdeb0) at ../src/parser/Script.cpp:93
#11 0x00005555556229e0 in std::_Function_handler<Escargot::Value(), Escargot::Script::sandboxExecute(Escargot::ExecutionState&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/7/bits/std_function.h:302
#12 0x00005555557a92a2 in std::function<Escargot::Value ()>::operator()() const (this=0x7fffffffdeb0) at /usr/include/c++/7/bits/std_function.h:706
#13 0x00005555557a7d87 in Escargot::SandBox::run(std::function<Escargot::Value ()> const&) (this=0x7fffffffde20, scriptRunner=...) at ../src/runtime/SandBox.cpp:36
#14 0x0000555555621aa6 in Escargot::Script::sandboxExecute (this=0x7ffff45eb4f0, state=...) at ../src/parser/Script.cpp:94
#15 0x00005555557c62c3 in eval (context=0x7ffff4663ed0, str=0x7ffff45f2a70, fileName=0x7ffff45f29d0, shouldPrintScriptResult=false) at ../src/shell/Shell.cpp:46
#16 0x00005555557c6c12 in main (argc=2, argv=0x7fffffffe1d8) at ../src/shell/Shell.cpp:129
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by DanielBallaSZTE** [comment]
Quick note on this issue:
In the `VMInstance.cpp` file any of the `static ObjectPropertyNativeGetterSetterData` functions that have either their `m_getter` or `m_setter` properties set to `nullptr` cause the same issue.
ie. calling `Object.defineProperty(r, <'source', 'global', 'ignorecase', 'multiline'>, {value: false});` reproduce the segmentation fault.
