### ISSUE TITLE
Assertion `!m_isDataProperty' failed in Escargot::ObjectGetResult::jsGetterSetter

### ISSUE THREAD

**Issue by renatahodovan** [pando-project/escargot#232]
###### Escargot version:

```
Checked revision: 958b293

Build command: cmake -H. -Bout -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=debug -DESCARGOT_OUTPUT=bin -GNinja && ninja -C out
```

###### OS:

```
Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
var handler = {
  get: function () {}
}

var proxy = new Proxy([ ], handler)
var boundFilter = Array.prototype.filter.bind(proxy)
boundFilter()
```

###### Backtrace:

```
escargot: ../src/runtime/Object.h:463: Escargot::JSGetterSetter* Escargot::ObjectGetResult::jsGetterSetter(): Assertion `!m_isDataProperty' failed.

bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6466801 in __GI_abort () at abort.c:79
#2  0x00007ffff645639a in __assert_fail_base (fmt=0x7ffff65dd7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x555555842b66 "!m_isDataProperty", file=file@entry=0x555555842a91 "../src/runtime/Object.h", line=line@entry=463, function=function@entry=0x5555558430e0 <Escargot::ObjectGetResult::jsGetterSetter()::__PRETTY_FUNCTION__> "Escargot::JSGetterSetter* Escargot::ObjectGetResult::jsGetterSetter()") at assert.c:92
#3  0x00007ffff6456412 in __GI___assert_fail (assertion=0x555555842b66 "!m_isDataProperty", file=0x555555842a91 "../src/runtime/Object.h", line=463, function=0x5555558430e0 <Escargot::ObjectGetResult::jsGetterSetter()::__PRETTY_FUNCTION__> "Escargot::JSGetterSetter* Escargot::ObjectGetResult::jsGetterSetter()") at assert.c:101
#4  0x00005555556d2285 in Escargot::ObjectGetResult::jsGetterSetter (this=0x7fffffffbb60) at ../src/runtime/Object.h:463
#5  0x00005555557af515 in Escargot::ProxyObject::get (this=0x7ffff4626070, state=..., propertyName=...) at ../src/runtime/ProxyObject.cpp:693
#6  0x00005555557a88d0 in Escargot::Object::length (this=0x7ffff4626070, state=...) at ../src/runtime/Object.cpp:888
#7  0x00005555556df788 in Escargot::builtinArrayFilter (state=..., thisValue=..., argc=1, argv=0x7fffffffbfb0, isNewExpression=false) at ../src/runtime/GlobalObjectBuiltinArray.cpp:942
#8  0x00005555556cd6f2 in Escargot::FunctionObject::processCall (this=0x7ffff4653cd0, state=..., receiverSrc=..., argc=1, argv=0x7fffffffbfb0, isNewExpression=false) at ../src/runtime/FunctionObject.cpp:357
#9  0x00005555555f50dc in Escargot::FunctionObject::call (state=..., callee=..., receiver=..., argc=1, argv=0x7fffffffbfb0, isNewExpression=false) at ../src/runtime/FunctionObject.h:111
#10 0x00005555556150e9 in Escargot::functionBindImpl (state=..., thisValue=..., calledArgc=1, calledArgv=0x7fffffffd600, isNewExpression=false) at ../src/parser/CodeBlock.cpp:179
#11 0x00005555556cd6f2 in Escargot::FunctionObject::processCall (this=0x7ffff461dd80, state=..., receiverSrc=..., argc=1, argv=0x7fffffffd600, isNewExpression=false) at ../src/runtime/FunctionObject.cpp:357
#12 0x00005555555f50dc in Escargot::FunctionObject::call (state=..., callee=..., receiver=..., argc=1, argv=0x7fffffffd600, isNewExpression=false) at ../src/runtime/FunctionObject.h:111
#13 0x00005555555f8209 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff7e6bcd0, programCounter=93824999022968, registerFile=0x7fffffffd5f0, initAddressFiller=0x0) at ../src/interpreter/ByteCodeInterpreter.cpp:529
#14 0x00005555556000ae in Escargot::ByteCodeInterpreter::tryOperation (state=..., code=0x555555bcde70, ec=0x7fffffffd6f0, env=0x7ffff462c8e0, programCounter=93824999022192, byteCodeBlock=0x7ffff7e6bcd0, registerFile=0x7fffffffd5f0) at ../src/interpreter/ByteCodeInterpreter.cpp:1983
#15 0x00005555555fa1c3 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff7e6bcd0, programCounter=93824999022192, registerFile=0x7fffffffd5f0, initAddressFiller=0x0) at ../src/interpreter/ByteCodeInterpreter.cpp:929
#16 0x0000555555625d97 in Escargot::Script::execute (this=0x7ffff4638100, state=..., isEvalMode=false, needNewEnv=false, isOnGlobal=true) at ../src/parser/Script.cpp:79
#17 0x0000555555625ee9 in Escargot::Script::<lambda()>::operator()(void) const (__closure=0x7fffffffd990) at ../src/parser/Script.cpp:92
#18 0x0000555555626ef2 in std::_Function_handler<Escargot::Value(), Escargot::Script::sandboxExecute(Escargot::ExecutionState&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:302
#19 0x00005555557bf72c in std::function<Escargot::Value ()>::operator()() const (this=0x7fffffffd990) at /usr/include/c++/7/bits/std_function.h:706
#20 0x00005555557be2df in Escargot::SandBox::run(std::function<Escargot::Value ()> const&) (this=0x7fffffffd900, scriptRunner=...) at ../src/runtime/SandBox.cpp:36
#21 0x0000555555625fc6 in Escargot::Script::sandboxExecute (this=0x7ffff4638100, state=...) at ../src/parser/Script.cpp:93
#22 0x00005555557dbd0c in eval (context=0x7ffff7e5bed0, str=0x7ffff46297f0, fileName=0x7ffff46296b0, shouldPrintScriptResult=false) at ../src/shell/Shell.cpp:47
#23 0x00005555557dc631 in main (argc=2, argv=0x7fffffffdcb8) at ../src/shell/Shell.cpp:128
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

**Comment by renatahodovan** [comment]
Fixed by #245 .
