### ISSUE TITLE
Segmentation fault in Escargot::ByteCodeInterpreter::interpret

### ISSUE THREAD

**Issue by renatahodovan** [pando-project/escargot#234]
###### Escargot version:

```
Checked revision: 958b293

Build command: cmake -H. -Bout -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=debug -DESCARGOT_OUTPUT=bin -GNinja && ninja -C out
```

###### OS:

```
Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
function test () {
  var $ = class $ { }
}

test()
```

###### Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555fa0f8 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff7e6bbb0, 
    programCounter=93824999008096, registerFile=0x7fffffffcc80, initAddressFiller=0x0)
    at ../src/interpreter/ByteCodeInterpreter.cpp:911
911	                registerFile[code->m_registerIndex] = new FunctionObject(state, NativeFunctionInfo(::Escargot::AtomicString::fromPayload(String::emptyString), implicitClassConstructor, 1, implicitClassConstructorCtor, NativeFunctionInfo::Flags::Strict | NativeFunctionInfo::Flags::Constructor | NativeFunctionInfo::Flags::ClassConstructor));
bt
#0  0x00005555555fa0f8 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff7e6bbb0, programCounter=93824999007392, registerFile=0x7fffffffcbc0, initAddressFiller=0x0) at ../src/interpreter/ByteCodeInterpreter.cpp:911
#1  0x00005555556000ae in Escargot::ByteCodeInterpreter::tryOperation (state=..., code=0x555555bca460, ec=0x7ffff461fed0, env=0x7ffff4638070, programCounter=93824999007328, byteCodeBlock=0x7ffff7e6bbb0, registerFile=0x7fffffffcbc0) at ../src/interpreter/ByteCodeInterpreter.cpp:1983
#2  0x00005555555fa1c3 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff7e6bbb0, programCounter=93824999007328, registerFile=0x7fffffffcbc0, initAddressFiller=0x0) at ../src/interpreter/ByteCodeInterpreter.cpp:929
#3  0x00005555556ce948 in Escargot::FunctionObject::processCall (this=0x7ffff4631120, state=..., receiverSrc=..., argc=0, argv=0x7fffffffd610, isNewExpression=false) at ../src/runtime/FunctionObject.cpp:536
#4  0x00005555555f50dc in Escargot::FunctionObject::call (state=..., callee=..., receiver=..., argc=0, argv=0x7fffffffd610, isNewExpression=false) at ../src/runtime/FunctionObject.h:111
#5  0x00005555555f8209 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff7e6bcd0, programCounter=93824999010032, registerFile=0x7fffffffd5f0, initAddressFiller=0x0) at ../src/interpreter/ByteCodeInterpreter.cpp:529
#6  0x0000555555625d97 in Escargot::Script::execute (this=0x7ffff4638730, state=..., isEvalMode=false, needNewEnv=false, isOnGlobal=true) at ../src/parser/Script.cpp:79
#7  0x0000555555625ee9 in Escargot::Script::<lambda()>::operator()(void) const (__closure=0x7fffffffd980) at ../src/parser/Script.cpp:92
#8  0x0000555555626ef2 in std::_Function_handler<Escargot::Value(), Escargot::Script::sandboxExecute(Escargot::ExecutionState&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:302
#9  0x00005555557bf72c in std::function<Escargot::Value ()>::operator()() const (this=0x7fffffffd980) at /usr/include/c++/7/bits/std_function.h:706
#10 0x00005555557be2df in Escargot::SandBox::run(std::function<Escargot::Value ()> const&) (this=0x7fffffffd8f0, scriptRunner=...) at ../src/runtime/SandBox.cpp:36
#11 0x0000555555625fc6 in Escargot::Script::sandboxExecute (this=0x7ffff4638730, state=...) at ../src/parser/Script.cpp:93
#12 0x00005555557dbd0c in eval (context=0x7ffff7e5bed0, str=0x7ffff46297f0, fileName=0x7ffff46296b0, shouldPrintScriptResult=false) at ../src/shell/Shell.cpp:47
#13 0x00005555557dc631 in main (argc=2, argv=0x7fffffffdca8) at ../src/shell/Shell.cpp:128
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

**Comment by renatahodovan** [comment]
Fixed by #203
